services:
    _defaults:
        autowire: true
        autoconfigure: true
    security.token_storage:
        class: Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage
        public: true
    Smug\FrontendFormBundle\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    
    Smug\FrontendFormBundle\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Doctrine\Persistence\ObjectManager: '@doctrine.orm.default_entity_manager'
